version: '3.4'
services:
  frontend:
    build: .
    command: yarn start -H 0.0.0.0 -p 3000
    volumes:
      - ./app/
      - ./app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
