version: '3.4'
services:
  backend:
    build: .
    command: yarn dev
    volumes:
      - ./app/
      - ./app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  db:
    image: mariadb
    restart: always
